/**
 * /usr/local/bin/nexaas wrapper install + migration (#259).
 *
 * The operator's CLI must run the compiled dist with
 * `--conditions=production` — the same #37 lesson the worker unit
 * learned: direct node invocation (no npx/npm wrappers that swallow
 * output or escape cgroups), compiled JS (no tsx cold-start in the hot
 * path). Early deployments hand-wrote `exec npx tsx .../src/index.ts`
 * wrappers; `nexaas upgrade` migrates those in place.
 */

import { existsSync, readFileSync } from "fs";
import { execSync } from "child_process";
import { join } from "path";

export const WRAPPER_PATH = "/usr/local/bin/nexaas";
const GENERATED_MARKER = "Generated by nexaas";

export type InstallResult = "installed" | "migrated" | "current" | "skipped-custom";

function wrapperContent(nexaasRoot: string, nodeBin: string): string {
  return `#!/bin/bash
# ${GENERATED_MARKER} (#259). Do not edit — nexaas init/upgrade rewrites this file.
set -a
[ -f "${nexaasRoot}/.env" ] && source "${nexaasRoot}/.env"
set +a
CLI="${nexaasRoot}/packages/cli/dist/index.js"
if [ ! -f "$CLI" ]; then
  echo "nexaas: compiled CLI missing at $CLI — run: cd ${nexaasRoot} && npm run build" >&2
  exit 1
fi
cd "${nexaasRoot}"
exec "${nodeBin}" --conditions=production "$CLI" "$@"
`;
}

/**
 * Write (or migrate) the wrapper. Idempotent — rewrites only when content
 * differs. Refuses to clobber a file that doesn't look like a nexaas
 * wrapper (no reference to packages/cli) so a deliberate custom shim
 * survives; everything else at that path is ours by definition.
 */
export function installCliBinary(nexaasRoot: string, nodeBin?: string): InstallResult {
  const detected = nodeBin ?? (() => {
    try { return execSync("which node", { encoding: "utf-8", stdio: "pipe" }).trim(); }
    catch { return ""; }
  })();
  const node = detected || "/usr/bin/node";

  const desired = wrapperContent(nexaasRoot, node);

  let existing: string | null = null;
  if (existsSync(WRAPPER_PATH)) {
    try { existing = readFileSync(WRAPPER_PATH, "utf-8"); } catch { existing = null; }
  }

  if (existing === desired) return "current";
  if (existing && !existing.includes("packages/cli")) return "skipped-custom";

  const wasLegacy = !!existing && !existing.includes(GENERATED_MARKER);

  // sudo tee — same write path init uses for the systemd unit; the CLI
  // often runs as the workspace user, not root.
  execSync(`sudo tee ${WRAPPER_PATH} > /dev/null && sudo chmod 755 ${WRAPPER_PATH}`, {
    input: desired,
    stdio: ["pipe", "pipe", "pipe"],
  });

  // Verify the write landed (masked sudo / readonly fs would fail silently
  // through exec-swallowing wrappers).
  const onDisk = readFileSync(WRAPPER_PATH, "utf-8");
  if (onDisk !== desired) {
    throw new Error(`failed to write ${WRAPPER_PATH} — check sudo permissions`);
  }

  return existing === null ? "installed" : wasLegacy ? "migrated" : "installed";
}

/** True when the wrapper is absent or still the legacy npx-tsx form. */
export function cliBinaryNeedsMigration(): boolean {
  if (!existsSync(WRAPPER_PATH)) return true;
  try {
    const content = readFileSync(WRAPPER_PATH, "utf-8");
    return !content.includes(GENERATED_MARKER);
  } catch {
    return true;
  }
}

/** Exposed for unit tests — the exact bytes installCliBinary writes. */
export function renderWrapper(nexaasRoot: string, nodeBin: string): string {
  return wrapperContent(nexaasRoot, nodeBin);
}
